apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-0
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: mongo-pv-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-1
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-2
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv-2
